title: "Cayman"
description: "Cayman is a clean, responsive theme for GitHub Pages."
show_downloads: true
google_analytics: # Add your Google Analytics ID here, or leave it blank
theme: jekyll-theme-cayman
